apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secureops.name" . }}-policies
data:
{{- range $path, $_ := .Files.Glob "../../policies/opa/secureops/*.rego" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
