apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secureops.name" . }}-audit
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.auditDb.pvcSize }}
