#!/usr/bin/env bash
# scenario_b_opa_denial.sh
# Operator cheat-sheet: OPA denies scale_workload to 0 in demo-prod (tier=prod).
# Claude then proposes restart as a safe alternative; that is allowed.
set -euo pipefail

echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Scenario B — OPA denial: scale to zero in prod        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "▶ CLAUDE DESKTOP PROMPT (part 1 — the denial):"
echo "  \"Scale the checkout deployment in demo-prod to 0 replicas.\""
echo ""
echo "── PRE-CHECK: namespace label ──────────────────────────────"
kubectl get namespace demo-prod --show-labels
echo ""
echo "── PRE-CHECK: PDB in demo-prod ─────────────────────────────"
kubectl -n demo-prod get pdb
echo ""
echo "── WHAT TO EXPECT — denial flow ────────────────────────────"
echo "  1. OPA evaluates: tool=scale_workload, tier=prod, replicas=0"
echo "     → allow: false, reasons=[prod_scale_zero_denied]"
echo "  2. MCP tool returns: status=denied_opa"
echo "  3. NO patch is made to the deployment"
echo "  4. Audit row written with result.status=denied_opa"
echo ""
echo "── VERIFY denial ───────────────────────────────────────────"
echo ""
echo "  # Replica count must still be 3:"
echo "  kubectl -n demo-prod get deploy checkout -o jsonpath='{.spec.replicas}'"
echo "  # Expected: 3"
echo ""
echo "  # Audit row for the denial:"
echo "  sqlite3 \$SECUREOPS_AUDIT_DB \\"
echo "    'SELECT row_id, json_extract(payload_json,\"$.proposal.tool_name\"), json_extract(payload_json,\"$.result.status\"), json_extract(payload_json,\"$.result.opa_reasons\") FROM audit_rows ORDER BY row_id DESC LIMIT 1'"
echo "  # Expected: scale_workload | denied_opa | [\"prod_scale_zero_denied\"]"
echo ""
echo "▶ CLAUDE DESKTOP PROMPT (part 2 — explain):"
echo "  \"Why was that denied? Explain the OPA decision.\""
echo ""
echo "── WHAT TO EXPECT — explain_opa_decision ───────────────────"
echo "  Tool: explain_opa_decision"
echo "  Claude reads the audit row, queries OPA /data/secureops/allow"
echo "  with the original input, returns human-readable explanation:"
echo "    'The scale_workload call was blocked because demo-prod is labelled"
echo "     tier=prod and the requested replica count is 0.  Policy rule:"
echo "     secureops.allow.prod_scale_zero.'"
echo ""
echo "▶ CLAUDE DESKTOP PROMPT (part 3 — safe alternative):"
echo "  \"OK, don't scale it. Instead, restart the checkout deployment in demo-prod.\""
echo ""
echo "── WHAT TO EXPECT — restart allowed ────────────────────────"
echo "  1. OPA evaluates: tool=restart_deployment, tier=prod"
echo "     → allow: true (restart is not blocked by any policy rule)"
echo "  2. TokenRequest minted for secureops-action-restart-deployment-demo-prod"
echo "  3. PATCH deployment/checkout in demo-prod"
echo "  4. Audit row with status=allowed_executed"
echo ""
echo "── VERIFY restart ──────────────────────────────────────────"
echo ""
echo "  kubectl -n demo-prod rollout status deploy/checkout"
echo ""
echo "  sqlite3 \$SECUREOPS_AUDIT_DB \\"
echo "    'SELECT row_id, json_extract(payload_json,\"$.proposal.tool_name\"), json_extract(payload_json,\"$.result.status\") FROM audit_rows ORDER BY row_id DESC LIMIT 3'"
echo ""
echo "── EXPECTED OUTPUT SUMMARY ─────────────────────────────────"
echo "  scale attempt: status=denied_opa, replicas unchanged"
echo "  restart:       status=allowed_executed"
echo "  Audience takeaway: LLM cannot override OPA; audit trail shows both."
echo ""
